#-------------------------------
# General Site Settings

menu:
- {name: 'Portfolio', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Website Portfolio for Michael Santacroce'
  # rel-author: 'https://plus.google.com/u/0/#'
  # rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-123662218-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: |
  #### Who are you?

  Hello!

  My name is Michael Santacroce, and I'm currently (as of 3/12/2025) a Member of Technical Staff at Microsoft AI. 

  I pursue work that I find technically interesting and societally impactful. I love learning about and pushing the boundaries on *all* aspects of Deep Learning and Large Language Models. For the last ~2 years, I have focused mainly on LLM post-training (online and offline) and synthetic data generation. However, I'm interested in the full stack, from writing performant training code to pushing downstream performance using the latest algorithms and techniques.

  It's my firm belief that having an ever-expanding understanding of the full, end-to-end stack for model creation produces greater models.
  
  I graduated from the University of Cincinnati in 2019 with a Bachelor's and Master's, both in Computer Engineering. Since then, I've been fortunate to learn from incredibly talented researchers and engineers while working on many projects. In this time, I've learned hard lessons and honed my skills, and I'm proud to be at MAI! 

  On this site you can find things that I've worked on, both professionally and for fun.

  <img src="../assets/img/michaelsantacroce.jpg" alt="" style="width: 60%; display: block; margin:auto;"/>



contact: |
  #### How do I reach you?

  Please contact me via email at [msantacr23@gmail.com](mailto:msantacr23@gmail.com) for any questions or requests.

  Also be sure to visit my [Github page](https://github.com/santacml/)!




#-------------------------------
# Work Section

projects:
- {name: 'Research', folder: 'research', file: 'projects/research.html'}
# - {name: 'Self-Study', folder: 'selfstudy', file: 'projects/selfstudy.html'}
- {name: 'Co-Ops', folder: 'coops', file: 'projects/coops.html'}
- {name: 'Optimal Moon Landing', folder: 'dynamic_optimization', file: 'projects/dynamic_optimization.html'}
- {name: 'Hello_Compiler', folder: 'hello_compiler', file: 'projects/hello_compiler.html'}
- {name: 'EECS Student Magazine', folder: 'magazine', file: 'projects/magazine.html'}
- {name: 'Websites', folder: 'websites', file: 'projects/websites.html'}
- {name: 'Student Groups', folder: 'studentgroups', file: 'projects/studentgroups.html'}

#-------------------------------
# Contact Section

social:
# - {icon: 'twitter', link: '#'}
# - {icon: 'instagram', link: '#'}
- {icon: 'github', link: 'https://github.com/santacml/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/santacrocemichael/'}
# - {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
